name: odoochat
description: Dart package to connect to Odoo chat
version: 1.0.0
homepage: https://github.com/correaleyval/odoochat_flutter

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  dio: ^4.0.0
  cookie_jar: ^3.0.1
  dio_cookie_manager: ^2.0.0

dev_dependencies:
  pedantic: ^1.9.0
  test: ^1.14.4
