name: odoochat
description: Dart package to connect to Odoo Discuss Module
version: 2.0.0
homepage: https://www.luisciber.com
repository: https://github.com/luiscib3r/odoochat_flutter
issue_tracker: https://github.com/luiscib3r/odoochat_flutter/issues
topics: [odoo, chat, messaging]

environment:
  sdk: ^3.0.0

dependencies:
  cookie_jar: ^4.0.8
  dio: ^5.4.0
  dio_cookie_manager: ^3.1.1
  equatable: ^2.0.5
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  pretty_dio_logger: ^1.3.1
  retrofit: ^4.0.3

dev_dependencies:
  build_runner: ^2.4.8
  freezed: ^2.4.6
  json_serializable: ^6.7.1
  pedantic: ^1.9.0
  retrofit_generator: ^8.0.6
  very_good_analysis: ^5.1.0
