name: odoochat_example
description: 'Odoo Chat Example'

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.4 <4.0.0'

dependencies:
  bloc: ^8.1.2
  cupertino_icons: ^1.0.2
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_chat_types: ^3.6.2
  flutter_chat_ui: ^1.6.10
  flutter_html: ^2.2.1
  flutter_login: ^5.0.0
  freezed_annotation: ^2.4.1
  intl: ^0.19.0
  odoochat:
    path: ../..

dev_dependencies:
  build_runner: ^2.4.8
  flutter_test:
    sdk: flutter
  freezed: ^2.4.6
  very_good_analysis: ^5.1.0

flutter:
  uses-material-design: true
